---
driver:
  name: vagrant
  network:
  synced_folders:
    - [".", "/vagrant", "create: true"]

provisioner:
  name: chef_zero
  require_chef_omnibus: 12.3.0
platforms:
  - name: oel-6.6
    driver_config:
       box: boxcutter/oel66
#      box: oel66
#      box_url: https://s3.amazonaws.com/gehc.preprod.useast1.swrepo/Platforms/Vagrant/oel66-nocm12.2.1-1.0.15.box
  - name: centos-6.6
    driver_config:
      box: chef/centos-6.6
  - name: centos-7.0
    driver_config:
      box: chef/centos-7.0
  - name: centos-7.1
    driver_config:
      box: chef/centos-7.1

suites:
  - name: default
#    data_bags_path: 'D:/GEGDC/KS309342/Downloads/Chef/data_bags'
#    encrypted_data_bag_secret_key_path: 'D:/GEGDC/KS309342/Downloads/Chef/.chef/encrypted_data_bag_secret.pem'
    busser:
      sudo: true
    run_list:
      - recipe[guacamole::default]

