---
driver:
  name: docker
  use_sudo: false
  require_chef_omnibus: true

platforms:
- name: centos
  driver_config:
    image: "centos"
    platform: "rhel"
    dockerfile: Dockerfile

suites:
  - name: default
    run_list:
      - recipe[guacamole::default]

